// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Starlemon.Models;

namespace Starlemon.Models.Migrations
{
    [DbContext(typeof(StarlemonContext))]
    [Migration("20190625151001_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Starlemon.Models.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Node");
                });

            modelBuilder.Entity("Starlemon.Models.Video", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Starlemon.Models.VideoPage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PageId");

                    b.Property<string>("Remark");

                    b.Property<long>("VideoId");

                    b.Property<string>("VideoPath")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("VideoId", "PageId");

                    b.ToTable("VideoPages");
                });

            modelBuilder.Entity("Starlemon.Models.VideoPageNode", b =>
                {
                    b.Property<long>("VideoPageId");

                    b.Property<int>("NodeId");

                    b.HasKey("VideoPageId", "NodeId");

                    b.HasIndex("NodeId");

                    b.ToTable("VideoPageNode");
                });

            modelBuilder.Entity("Starlemon.Models.VideoPage", b =>
                {
                    b.HasOne("Starlemon.Models.Video", "Video")
                        .WithMany("Pages")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Starlemon.Models.VideoPageNode", b =>
                {
                    b.HasOne("Starlemon.Models.Node", "Node")
                        .WithMany("StoredPages")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Starlemon.Models.VideoPage", "VideoPage")
                        .WithMany("Nodes")
                        .HasForeignKey("VideoPageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
